# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
imports:
    - { resource: legacy_aliases.yml }
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    AppBundle\Service\MarkdownTransformer:
        public: true
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    AppBundle\Twig\MarkdownExtension: ~
        #arguments: ['@app.markdown_transformer']

    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']

    AppBundle\Security\LoginFormAuthenticator: ~

    AppBundle\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }
